// <auto-generated />
namespace DataModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addFK2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFK2));
        
        string IMigrationMetadata.Id
        {
            get { return "202001051207453_addFK2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
